language: node_js
node_js:
- node
deploy:
  provider: firebase
  project: eede
  token:
    secure: IfVDWHitipEPB1aYFdcEztsOr7UpTLxbRTtp0YozBRghzvxBgBIDtbUq+Jc3tKWfE4EeMc9FXPzfiWqTgSIUOpW/5dUeJioW4JpJ5Ugwzqr3bMY1bVp4GdDTNnz/Hn5RFO6hYeeTJFKfvqpEjSTb4xw3/mST7Oveg7wWiSlYxJ83IWY56ogL03TkEtx3g+IgaocHW42WLfyDrtr9LyVwtSOKZ+04/oMfkAg3gTxxNHqq4zAIa8AAiWKuAbNm6JyY9ruj07Bkby8U8LbqAUaATgo3gFpJJ52AK9YiIKmSLXKItOMVo7RmkuzoNo+LNEacIpJn5culN3Ns4V7FEW8THoXjVo0yNAYVeIEceTHqddEKylx6dIrjrErTTFMlslMiphmcnBAvtQCkh1kv5hN4mBL8lUXXh5uL/51yCO6J20Dw/zlJO6MCJjmsT3ZMDJo6usjCCIYLbp2JS0373I1I/MBri6WWBO71qx4WFEDV/kJYDvTdogBLNBl1ADgqUPdwOtkHomjK2z2NROqtQJIO1attrPY9JhFFddqJwrdqMuskc0KGNhkPDsbR1QBwlW5c6p7E02EIrtU5xwKkhEHXxNRydOZgD7CnoZZVZRx7Nw0GTeeqSDzV//V4kCOZ3oadptfJN5nKDNf8mkzXexQdqBiD4eoO4PrLpcJR6Iex004=
    skip_cleanup: true
script:
- npm install
- npm run build
