language: node_js
node_js:
- node
deploy:
  provider: firebase
  token: "$FIREBASE_TOKEN"
    secure: "nmm6l3JL10g7A5u7WY/oMcxzo0GmltM5ZwCNmMnRHKY85yWYT7azK/IkE5JatUcIrfmOR3cHyqTwOMGE1pxjPxr36vMP/kdPY79x7P3CrDhFwYJV9U3pReTHgEzRJstlTmagBRLuSMZK/xlLNqPAsfS7JCmTybXHaqU0M+YEb7KSmVvTp8pMoItygqlY7/wOwGPHuIEW6cFDmSKnTcn0+AMwvCPOpr7GSRUDPOw83z09Xm42SBv6dJMxL3sb/Q8yjICrMdQ0Ml3SavoOFLt3qg8YZltAQhH3vU1smT7tNlGdzgvm05c53leJnswDT6WHUj9UOHoSgKXwdYzIdedS5LB2T9Fg4noePnSPOnquRHozdXvUyrZlOEQxr30N1tJzxIz6dAmXi1SYGcG/kHk3WXENxvLXW6vzQDAezpMykHr5g/eusamGbu9krKffGN78K7ay2EmGly+KQTPiQp2tZJi9f4ae+rPZXiKzFU1mlcrcqQbnjAeZ/KSFaecZVIHfrvftnFey6nO5XeA0Gq4kxaA0iSfd6x7aweqLEpe+KrW7hc7AKFsYY6J0+eu0M6iG1gOiRiYMyPnrFO0QhBbPzUyv+F8lHAnBzMVZiIN661q0Jzn0efYV7MhnJS7VLjpN5oI/0y1AORkvTTI6qGm1svkO5J8TLc4HtngkY9q/jMQ="
  skip_cleanup: true
script:
- npm install
- npm run build
