language: node_js
node_js:
- node
deploy:
  provider: firebase
  project: "eede-d8ccf"
  token:
    secure: "MDDIr/QqQmXMA/J0K1Cq3pDbWjB2FjzAhZ9tM0P7thh3EdTaQ99qn1MgExMxv2uCpE7kChR4R4H1TVMYjA+TVxxURwO2ktG4aMTXN1kFbhuCLyrKmS2IiFEqF71JN307cjAwkxoXBy2f7gVbWDB2sXyEfQ+aRHOOngFyjeUtJrGsXWLCxG7wVxRes/TFK6mKz6/FyO2uR9C30s9ot/A3Rsti8tN4mdVoNPYAjrxZWkBu6UuqMqxG7BOiT3jaD5QSmVh7QpMR9eco2Hscg44aC7dTcWJeEBn49nv4Ac7WjVlLx4KKxnur7FvVLzZrPFPbQJhkv8BNSsMvMe0BnamY4HpMsJVgqfF7tgf/sUo9MVRA9vLZ8WE4rJRDdgTEu6bpyy1nUZkGEr4uwE8siic+GwWd/dl9P4YABR9nPQU1BkyH2ng41HD0wAWanjHQeBX/QuItE5q3xetGuaQjUsJ9F6NYvFVnXoe25Keru5SW+h+rLFyl0ZGn2RN56h7DuCARHBlUyz+HxBovnpjMN46KQ++2mlGMaP1+wWuZVBE3ZjsHvdKDB56B8/vmfbyADvaXKYreygi8PaoP7lDKTnqLqm1nvqspDr3dB9FJwg/lDdd9ncsrb8heFAM95GegE7szQnl4w+odDAwjpL8O/pozwxM/68ZVZwQDDaBkCePS/9g="
script:
- npm install
- npm install -g firebase-tools
- cd ./functions
- npm install
- cd ..
- npm run build
notifications:
  slack:
    secure: "GZMlB0i7I9lyqKuVTP9UJlshaKU7vafbLqMax+6B/mf2oXV+pCdAk2EKxaIcqDsaEOMmbfjsQ1rUcFKX2+orm0qToyGc0kHujIdpeJJ+FS5leGvgehbWbr1Q4o38HabsJX4OiT1u+IohYkHMySDcK/ExdC0tajTNfHhJQtZITxK6zF9+2kJ7KK0ujbBYXVUyGjd3+FhBul0LETrU3szzve2YpRubFpDl5kHH27KMS2S7qmC0dWFJXb+yS6kw7bdYuu8lB9BjMJLldODdnWOuD8VXOtm2zs28YKhTi8UIZYXj3LGSi3b5BifkxTQzPl/6XhR07c4WtHR6gRUQTxEOE7UBNvYBtKEthxqbDV3Is9aFr+cDAqP1dAMnxVyLZi1psYo6hMWRv7srz8aL9VxRyJtSRIDCLPhWQXPa3WUle7I6kSoi8rDABPbTS5r9Vvqv9jvFYW0060Gs9SuMPgjT87eZbjV5OblhgyEqYJjVOleLaGZtAaxwv+M11MizmcpK7Kkekltp4orLE10GI9RY9/IxjfqAeRt7SlPlo1DmZHMFQK5CpyTqoKByV7QQkZjGbKeP+1mSKFx/Q+EeuOQGy3BGXoC6IL6ZnFUfgG60vVjLVtM1vKBrOB3QafePHXmFtYUwpazewL+chmDpYKlQRpHOQlhb6nsz8d4zAdZg8pM="
