language: node_js
node_js:
- node
deploy:
  provider: firebase
  project: "eede-d8ccf"
  token:
    secure: "cKX+csSsa+dDZx7H7KrPnmBFGEQu2ZgA6NzT53gz/+5qJUmFImiOKcTlgChxmR1TLvjkmN8VJu9iaojMU1/KS2Ww9L5P2eCataw0IudvehlT2gGBZWPHuDyg+SHpiL+2Zu7b60wjLTiTaDtDFvrFNzNTj+xQw7BNcih3PN2Le+47DdlnsDNbYinI5jREpYSlUxdgpORUxO32Y55fbTuQ9AYGQTbJmPo15ocQibCksXNHZW70Ed2rf7+GNWOzrlI32haJXdSJl1BBWxKUWprKXbA1Oixa82pettmF8Ow72yT6mDK27fIgSV/T+KnovMrS1IgKO4eL6IE1/1rTKw3GGR9Z55FREew8Zrcc56IS0wB2NdmfjoDfjlj1WkdNQvsKKUNRsxm4PVwnAnKYpNvr3sNjooDi1cLE4uOfK9IEQaAIWR9SiIAHTel8abH0AiP5NZnHZ9pxmZXhbohBGi8OFimLAROo3MrhqUh5+GD4Td/fcz/lzTsS0ISbsarU5JtPQ1Fl1elcNcMm3sAHpIAKDo3B0ejHdySpFegqIpQNopDCK9zVGe1C68mQfG5CLe65Clq0CMARnVCWCQZTO46s90gfnOUwX6mODw0SZ0YWHpo471qttm/iURjolzek+8pQUVFzvg4rnQh7ZfVCHW79+e7KYx94TOrzbsqnRmuLXhE="
  skip_cleanup: true
script:
- npm install
- npm run build
notifications:
  slack:
    secure: "GZMlB0i7I9lyqKuVTP9UJlshaKU7vafbLqMax+6B/mf2oXV+pCdAk2EKxaIcqDsaEOMmbfjsQ1rUcFKX2+orm0qToyGc0kHujIdpeJJ+FS5leGvgehbWbr1Q4o38HabsJX4OiT1u+IohYkHMySDcK/ExdC0tajTNfHhJQtZITxK6zF9+2kJ7KK0ujbBYXVUyGjd3+FhBul0LETrU3szzve2YpRubFpDl5kHH27KMS2S7qmC0dWFJXb+yS6kw7bdYuu8lB9BjMJLldODdnWOuD8VXOtm2zs28YKhTi8UIZYXj3LGSi3b5BifkxTQzPl/6XhR07c4WtHR6gRUQTxEOE7UBNvYBtKEthxqbDV3Is9aFr+cDAqP1dAMnxVyLZi1psYo6hMWRv7srz8aL9VxRyJtSRIDCLPhWQXPa3WUle7I6kSoi8rDABPbTS5r9Vvqv9jvFYW0060Gs9SuMPgjT87eZbjV5OblhgyEqYJjVOleLaGZtAaxwv+M11MizmcpK7Kkekltp4orLE10GI9RY9/IxjfqAeRt7SlPlo1DmZHMFQK5CpyTqoKByV7QQkZjGbKeP+1mSKFx/Q+EeuOQGy3BGXoC6IL6ZnFUfgG60vVjLVtM1vKBrOB3QafePHXmFtYUwpazewL+chmDpYKlQRpHOQlhb6nsz8d4zAdZg8pM="
